#!/usr/bin/env bash

#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.
# By: Imanol Asolo

# Check the number of parameters
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
# Assign parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Display a message to the user
echo "Starting file transfer..."

# Transfer file using scp with strict host key verification disabled
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Verify the success of the transfer
if [ $? -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
    exit 1
fi