#!/usr/bin/env bash
# Configures a new HAProxy as a load balancer

# Update package list and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Configure HAProxy configuration file to distribute requests using a roundrobin algorithm
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend sammykingx.tech
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 525303-web-01 54.173.122.164:80 check
    server 525303-web-02 100.26.235.137:80 check
EOF

# Restart HAProxy service
service haproxy restart

